### ISSUE TITLE
Question about the fine-tuning strategy

### ISSUE THREAD

**Issue by PluseLin** [dmis-lab/LIQUID#1]
Hello!
Recently, I  plan to use your dataset as a baseline for some explorations. I want to know which strategy you used during fine-tuning:
1. Merging the LIQUID dataset with the MultiSpanQA training data and fine-tuning them together.
2. Performing "pre-fine-tuning" on LIQUID dataset first, followed by fine-tuning on MultiSpanQA.

**Comment by nowkim** [comment]
Hi @PluseLin, thanks for the question!

We used the second approach, where the model is first trained on synthetic data and then fine-tuned with human-labeled data. In the paper, this setup is referred to as the "D˜ → D" setting (see Section 3.4).

Hope this answer helps and feel free to ask any further questions!

**Comment by PluseLin** [comment]
> Hi @PluseLin, thanks for the question!
> 
> We used the second approach, where the model is first trained on synthetic data and then fine-tuned with human-labeled data. In the paper, this setup is referred to as the "D˜ → D" setting (see Section 3.4).
> 
> Hope this answer helps and feel free to ask any further questions!

I see. Thanks for your reply!
